apiVersion: v1
kind: Namespace
metadata:
  name: bk

---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: bk
  labels:
    app: cart
spec:
  type: LoadBalancer
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bk
  labels:
    app: cart
  name: cart
spec:

  selector:
    matchLabels:
      app: cart
  template:

    metadata:
      labels:
        app: cart
    spec:

      containers:
        - image: gcr.io/pgtm-jlong/cart
          imagePullPolicy: Always
          name: cart

