---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: bk
  name: cart-postgres-pv-volume
  labels:
    type: local
    app: cart-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: bk
  name: cart-postgres-pv-claim
  labels:
    app: cart-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-postgres
  template:
    metadata:
      namespace: bk
      labels:
        app: cart-postgres
    spec:
      containers:
        - image: "postgres:latest"
          imagePullPolicy: IfNotPresent
          name: cart-postgres
          env:
            - name: POSTGRES_USER
              value: bk
            - name: PGUSER
              value: bk
            - name: POSTGRES_PASSWORD
              value: bk
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  namespace: bk
  name: cart-postgres
  labels:
    app: cart-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
#      nodePort: 31070
  selector:
    app: cart-postgres
